name:                mailer
version:             0.1.0.0
github:              "jborkowski/mailer"
license:             BSD3
author:              "Jonatan Borkowski"
maintainer:          "jonatan.borkowski@pm.me"
copyright:           "2020 Jonatan Borkowski"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/jborkowski/mailer#readme>

ghc-options:
- -fplugin=Polysemy.Plugin

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies

dependencies:
- base >= 4.7 && < 5
- containers
- polysemy
- polysemy-plugin
- polysemy-zoo
- errors
- servant
- servant-server
- aeson
- wai
- warp
- mtl
- optparse-generic
- sqlite-simple
- uuid
- time
- HaskellNet
- HaskellNet-SSL
- bytestring
- text
- lens
- lens-aeson
- mime-mail

library:
  source-dirs: src

executables:
  mailer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mailer

tests:
  mailer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mailer
